# Generated by Django 3.2.9 on 2025-12-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='dietary_labels',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
