# Generated by Django 3.2.9 on 2025-12-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_dietary_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(default='Other', max_length=100),
        ),
    ]
